In [2]:
import pandas as pd

# Recriando o conjunto de treinamento exato da imagem
dados = {
    'Idade': ['infantil', 'infantil', 'infantil', 'infantil', 'adolescente', 'adolescente', 'adolescente', 'adolescente', 'adolescente', 'adulto', 'adulto', 'adulto', 'adulto', 'adulto', 'adulto'],
    'Diagnóstico': ['miopia', 'miopia', 'hipermetropia', 'hipermetropia', 'miopia', 'miopia', 'miopia', 'hipermetropia', 'hipermetropia', 'miopia', 'miopia', 'miopia', 'hipermetropia', 'hipermetropia', 'hipermetropia'],
    'Astigmatismo': ['não', 'sim', 'não', 'sim', 'não', 'sim', 'não', 'não', 'sim', 'não', 'sim', 'sim', 'não', 'sim', 'não'],
    'Taxa lacrimal': ['reduzida', 'normal', 'normal', 'normal', 'reduzida', 'reduzida', 'normal', 'reduzida', 'normal', 'normal', 'normal', 'normal', 'reduzida', 'normal', 'normal'],
    'Tipo de lente': ['nenhuma', 'gelatinosa', 'gelatinosa', 'dura', 'gelatinosa', 'nenhuma', 'dura', 'gelatinosa', 'dura', 'gelatinosa', 'dura', 'gelatinosa', 'nenhuma', 'gelatinosa', 'gelatinosa']
}

df = pd.DataFrame(dados)

# Ajustando o índice para começar em 1, igual à coluna '#' da imagem
df.index = range(1, len(df) + 1)
df.index.name = '#'

# Variáveis globais úteis para o Suavizador Laplaciano (alpha = 1) nos próximos exercícios
alpha = 1
classes = df['Tipo de lente'].unique()
qtd_classes = len(classes)
total_instancias = len(df)

print("Dataset carregado com sucesso!\n")
display(df)

Dataset carregado com sucesso!

          Idade    Diagnóstico Astigmatismo Taxa lacrimal Tipo de lente
#
1      infantil         miopia          não      reduzida       nenhuma
2      infantil         miopia          sim        normal    gelatinosa
3      infantil  hipermetropia          não        normal    gelatinosa
4      infantil  hipermetropia          sim        normal          dura
5   adolescente         miopia          não      reduzida    gelatinosa
6   adolescente         miopia          sim      reduzida       nenhuma
7   adolescente         miopia          não        normal          dura
8   adolescente  hipermetropia          não      reduzida    gelatinosa
9   adolescente  hipermetropia          sim        normal          dura
10       adulto         miopia          não        normal    gelatinosa
11       adulto         miopia          sim        normal          dura
12       adulto         miopia          sim        normal    gelatinosa
13       adulto  hipermetropia          não      reduzida       nenhuma
14       adulto  hipermetropia          sim        normal    gelatinosa
15       adulto  hipermetropia          não        normal    gelatinosa

In [5]:
# Características possíveis (tamanho do vocabulário V para o Laplace)
v_idade = len(df['Idade'].unique())
v_diag = len(df['Diagnóstico'].unique())
v_astig = len(df['Astigmatismo'].unique())
v_taxa = len(df['Taxa lacrimal'].unique())

# Paciente do Exercício 2
paciente = {
    'Idade': 'infantil',
    'Diagnóstico': 'hipermetropia',
    'Astigmatismo': 'não',
    'Taxa lacrimal': 'reduzida'
}

resultados_nb = {}

print("--- EXERCÍCIOS 1 e 2: Classificador Naive Bayes ---")

for c in classes:
    # Filtra o dataframe para a classe atual
    df_c = df[df['Tipo de lente'] == c]
    count_c = len(df_c)

    # Probabilidade a priori P(Classe) com Laplace
    p_classe = (count_c + alpha) / (total_instancias + alpha * qtd_classes)

    # Probabilidades condicionais com Laplace P(Atributo | Classe)
    # P(Idade | Classe)
    count_idade = len(df_c[df_c['Idade'] == paciente['Idade']])
    p_idade = (count_idade + alpha) / (count_c + alpha * v_idade)

    # P(Diagnóstico | Classe)
    count_diag = len(df_c[df_c['Diagnóstico'] == paciente['Diagnóstico']])
    p_diag = (count_diag + alpha) / (count_c + alpha * v_diag)

    # P(Astigmatismo | Classe)
    count_astig = len(df_c[df_c['Astigmatismo'] == paciente['Astigmatismo']])
    p_astig = (count_astig + alpha) / (count_c + alpha * v_astig)

    # P(Taxa lacrimal | Classe)
    count_taxa = len(df_c[df_c['Taxa lacrimal'] == paciente['Taxa lacrimal']])
    p_taxa = (count_taxa + alpha) / (count_c + alpha * v_taxa)

    # Cálculo final de Naive Bayes (não normalizado)
    prob_bruta = p_classe * p_idade * p_diag * p_astig * p_taxa
    resultados_nb[c] = prob_bruta

    print(f"\nClasse: {c}")
    print(f"P({c}) = {p_classe:.4f}")
    print(f"P(Idade={paciente['Idade']}|{c}) = {p_idade:.4f}")
    print(f"P(Diag={paciente['Diagnóstico']}|{c}) = {p_diag:.4f}")
    print(f"P(Astig={paciente['Astigmatismo']}|{c}) = {p_astig:.4f}")
    print(f"P(Taxa={paciente['Taxa lacrimal']}|{c}) = {p_taxa:.4f}")
    print(f"Probabilidade Bruta = {prob_bruta:.6f}")

# Normalização
soma_probs = sum(resultados_nb.values())
print("\n--- Probabilidades Normalizadas (Previsão Final) ---")
for c, prob in resultados_nb.items():
    prob_norm = prob / soma_probs
    print(f"P(Classe = {c} | Paciente) = {prob_norm * 100:.2f}%")

classe_vencedora = max(resultados_nb, key=resultados_nb.get)
print(f"\n>> PREVISÃO NAIVE BAYES: {classe_vencedora.upper()}")

--- EXERCÍCIOS 1 e 2: Classificador Naive Bayes ---

Classe: nenhuma
P(nenhuma) = 0.2222
P(Idade=infantil|nenhuma) = 0.3333
P(Diag=hipermetropia|nenhuma) = 0.4000
P(Astig=não|nenhuma) = 0.6000
P(Taxa=reduzida|nenhuma) = 0.8000
Probabilidade Bruta = 0.014222

Classe: gelatinosa
P(gelatinosa) = 0.5000
P(Idade=infantil|gelatinosa) = 0.2727
P(Diag=hipermetropia|gelatinosa) = 0.5000
P(Astig=não|gelatinosa) = 0.6000
P(Taxa=reduzida|gelatinosa) = 0.3000
Probabilidade Bruta = 0.012273

Classe: dura
P(dura) = 0.2778
P(Idade=infantil|dura) = 0.2857
P(Diag=hipermetropia|dura) = 0.5000
P(Astig=não|dura) = 0.3333
P(Taxa=reduzida|dura) = 0.1667
Probabilidade Bruta = 0.002205

--- Probabilidades Normalizadas (Previsão Final) ---
P(Classe = nenhuma | Paciente) = 49.56%
P(Classe = gelatinosa | Paciente) = 42.76%
P(Classe = dura | Paciente) = 7.68%

>> PREVISÃO NAIVE BAYES: NENHUMA

In [6]:
resultados_rb = {}

print("--- EXERCÍCIOS 3 e 4: Rede Bayesiana (Taxa Lacrimal dependente da Idade) ---")

for c in classes:
    df_c = df[df['Tipo de lente'] == c]
    count_c = len(df_c)

    # Probabilidades que continuam iguais ao Naive Bayes
    p_classe = (count_c + alpha) / (total_instancias + alpha * qtd_classes)

    count_idade = len(df_c[df_c['Idade'] == paciente['Idade']])
    p_idade = (count_idade + alpha) / (count_c + alpha * v_idade)

    count_diag = len(df_c[df_c['Diagnóstico'] == paciente['Diagnóstico']])
    p_diag = (count_diag + alpha) / (count_c + alpha * v_diag)

    count_astig = len(df_c[df_c['Astigmatismo'] == paciente['Astigmatismo']])
    p_astig = (count_astig + alpha) / (count_c + alpha * v_astig)

    # NOVA ESTRUTURA: P(Taxa lacrimal | Idade, Classe)
    # Quantas instâncias possuem ESSA classe E ESSA idade específica?
    df_c_idade = df_c[df_c['Idade'] == paciente['Idade']]
    count_c_idade = len(df_c_idade)

    # Dessas instâncias (mesma classe e idade), quantas têm a Taxa Lacrimal do paciente?
    count_taxa_idade = len(df_c_idade[df_c_idade['Taxa lacrimal'] == paciente['Taxa lacrimal']])

    # Aplicação de Laplace nesta condicional composta
    p_taxa_dada_idade_classe = (count_taxa_idade + alpha) / (count_c_idade + alpha * v_taxa)

    # Cálculo final da Rede Bayesiana
    prob_bruta = p_classe * p_idade * p_diag * p_astig * p_taxa_dada_idade_classe
    resultados_rb[c] = prob_bruta

    print(f"\nClasse: {c}")
    print(f"P(Taxa={paciente['Taxa lacrimal']} | Idade={paciente['Idade']}, Classe={c}) = ({count_taxa_idade} + {alpha}) / ({count_c_idade} + {alpha}*{v_taxa}) = {p_taxa_dada_idade_classe:.4f}")
    print(f"Probabilidade Bruta = {prob_bruta:.6f}")

# Normalização
soma_probs_rb = sum(resultados_rb.values())
print("\n--- Probabilidades Normalizadas da Rede Bayesiana ---")
for c, prob in resultados_rb.items():
    prob_norm = prob / soma_probs_rb
    print(f"P(Classe = {c} | Paciente) = {prob_norm * 100:.2f}%")

classe_vencedora_rb = max(resultados_rb, key=resultados_rb.get)
print(f"\n>> PREVISÃO REDE BAYESIANA: {classe_vencedora_rb.upper()}")

--- EXERCÍCIOS 3 e 4: Rede Bayesiana (Taxa Lacrimal dependente da Idade) ---

Classe: nenhuma
P(Taxa=reduzida | Idade=infantil, Classe=nenhuma) = (1 + 1) / (1 + 1*2) = 0.6667
Probabilidade Bruta = 0.011852

Classe: gelatinosa
P(Taxa=reduzida | Idade=infantil, Classe=gelatinosa) = (0 + 1) / (2 + 1*2) = 0.2500
Probabilidade Bruta = 0.010227

Classe: dura
P(Taxa=reduzida | Idade=infantil, Classe=dura) = (0 + 1) / (1 + 1*2) = 0.3333
Probabilidade Bruta = 0.004409

--- Probabilidades Normalizadas da Rede Bayesiana ---
P(Classe = nenhuma | Paciente) = 44.74%
P(Classe = gelatinosa | Paciente) = 38.61%
P(Classe = dura | Paciente) = 16.65%

>> PREVISÃO REDE BAYESIANA: NENHUMA

In [4]:
def gerar_tabelas_exercicio_1(df, alpha=1):
    atributos = ['Idade', 'Diagnóstico', 'Astigmatismo', 'Taxa lacrimal']
    target = 'Tipo de lente'
    classes = df[target].unique()

    print("--- EXERCÍCIO 1: TABELAS DE CONTAGENS E PROBABILIDADES SUAVIZADAS ---\n")

    for attr in atributos:
        # 1. Tabela de Contagem (Frequência)
        contagem = pd.crosstab(df[attr], df[target])

        # 2. Tabela de Probabilidades Suavizadas (Laplace)
        v = len(df[attr].unique()) # Tamanho do domínio do atributo

        # Aplicando a fórmula: (contagem + alpha) / (total_da_classe + alpha * v)
        prob_suavizada = contagem.copy().astype(float)
        for classe in classes:
            total_classe = len(df[df[target] == classe])
            prob_suavizada[classe] = (contagem[classe] + alpha) / (total_classe + alpha * v)

        print(f"Atributo: {attr}")
        print("Contagens:")
        display(contagem)
        print(f"Probabilidades Suavizadas (alpha={alpha}):")
        display(prob_suavizada.round(4))
        print("-" * 50)

gerar_tabelas_exercicio_1(df)

--- EXERCÍCIO 1: TABELAS DE CONTAGENS E PROBABILIDADES SUAVIZADAS ---

Atributo: Idade
Contagens:

Tipo de lente  dura  gelatinosa  nenhuma
Idade
adolescente       2           2        1
adulto            1           4        1
infantil          1           2        1

Probabilidades Suavizadas (alpha=1):

Tipo de lente    dura  gelatinosa  nenhuma
Idade
adolescente    0.4286      0.2727   0.3333
adulto         0.2857      0.4545   0.3333
infantil       0.2857      0.2727   0.3333

--------------------------------------------------
Atributo: Diagnóstico
Contagens:

Tipo de lente  dura  gelatinosa  nenhuma
Diagnóstico
hipermetropia     2           4        1
miopia            2           4        2

Probabilidades Suavizadas (alpha=1):

Tipo de lente  dura  gelatinosa  nenhuma
Diagnóstico
hipermetropia   0.5         0.5      0.4
miopia          0.5         0.5      0.6

--------------------------------------------------
Atributo: Astigmatismo
Contagens:

Tipo de lente  dura  gelatinosa  nenhuma
Astigmatismo
não               1           5        2
sim               3           3        1

Probabilidades Suavizadas (alpha=1):

Tipo de lente    dura  gelatinosa  nenhuma
Astigmatismo
não            0.3333         0.6      0.6
sim            0.6667         0.4      0.4

--------------------------------------------------
Atributo: Taxa lacrimal
Contagens:

Tipo de lente  dura  gelatinosa  nenhuma
Taxa lacrimal
normal            4           6        0
reduzida          0           2        3

Probabilidades Suavizadas (alpha=1):

Tipo de lente    dura  gelatinosa  nenhuma
Taxa lacrimal
normal         0.8333         0.7      0.2
reduzida       0.1667         0.3      0.8

--------------------------------------------------

In [7]:
print("--- EXERCÍCIO 3: TABELA DE PROBABILIDADE CONDICIONAL (CPT) ---")
print("P(Taxa Lacrimal | Idade, Tipo de Lente)\n")

# Criando a contagem tripla
cpt_counts = pd.crosstab([df['Idade'], df['Tipo de lente']], df['Taxa lacrimal'])

# Suavização Laplaciana para a CPT
v_taxa = len(df['Taxa lacrimal'].unique())
cpt_prob = cpt_counts.copy().astype(float)

# Itera sobre as combinações de Idade e Classe para calcular a probabilidade de cada Taxa
for idx in cpt_counts.index:
    total_combinacao = cpt_counts.loc[idx].sum()
    cpt_prob.loc[idx] = (cpt_counts.loc[idx] + alpha) / (total_combinacao + alpha * v_taxa)

print("Contagens Combinadas:")
display(cpt_counts)
print("\nProbabilidades Suavizadas (CPT da Rede Bayesiana):")
display(cpt_prob.round(4))

--- EXERCÍCIO 3: TABELA DE PROBABILIDADE CONDICIONAL (CPT) ---
P(Taxa Lacrimal | Idade, Tipo de Lente)

Contagens Combinadas:

Taxa lacrimal              normal  reduzida
Idade       Tipo de lente
adolescente dura                2         0
            gelatinosa          0         2
            nenhuma             0         1
adulto      dura                1         0
            gelatinosa          4         0
            nenhuma             0         1
infantil    dura                1         0
            gelatinosa          2         0
            nenhuma             0         1

Probabilidades Suavizadas (CPT da Rede Bayesiana):

Taxa lacrimal              normal  reduzida
Idade       Tipo de lente
adolescente dura           0.7500    0.2500
            gelatinosa     0.2500    0.7500
            nenhuma        0.3333    0.6667
adulto      dura           0.6667    0.3333
            gelatinosa     0.8333    0.1667
            nenhuma        0.3333    0.6667
infantil    dura           0.6667    0.3333
            gelatinosa     0.7500    0.2500
            nenhuma        0.3333    0.6667